/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victor Kreuz
 */
public class Pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbVacalos = new javax.swing.JCheckBox();
        jcbOveias = new javax.swing.JCheckBox();
        jcbPibis = new javax.swing.JCheckBox();
        jcbPeixis = new javax.swing.JCheckBox();
        jcbBoys = new javax.swing.JCheckBox();
        jcbPoicos = new javax.swing.JCheckBox();
        jbConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quais desses tipos de animais você possui em sua propriedade?");
        jLabel1.setToolTipText("");

        jcbVacalos.setText("Equinos");
        jcbVacalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVacalosActionPerformed(evt);
            }
        });

        jcbOveias.setText("Bovídeos");
        jcbOveias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOveiasActionPerformed(evt);
            }
        });

        jcbPibis.setText("Aves");
        jcbPibis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPibisActionPerformed(evt);
            }
        });

        jcbPeixis.setText("Psídeos");

        jcbBoys.setText("Bovinos");
        jcbBoys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBoysActionPerformed(evt);
            }
        });

        jcbPoicos.setText("Suínos");
        jcbPoicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPoicosActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbConfirmar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbOveias)
                                    .addComponent(jcbVacalos))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbBoys)
                                    .addComponent(jcbPeixis))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbPibis)
                            .addComponent(jcbPoicos))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbVacalos)
                    .addComponent(jcbBoys)
                    .addComponent(jcbPoicos))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPeixis)
                    .addComponent(jcbOveias)
                    .addComponent(jcbPibis))
                .addGap(18, 18, 18)
                .addComponent(jbConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbVacalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVacalosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbVacalosActionPerformed

    private void jcbPoicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPoicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPoicosActionPerformed

    private void jcbOveiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOveiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbOveiasActionPerformed

    private void jcbPibisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPibisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPibisActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        int variedadeAnimais = 0;
        String animaisMarcados = "";
        if (jcbVacalos.isSelected()) {
            variedadeAnimais++;
            animaisMarcados += "Equinos / ";
        }
        if (jcbOveias.isSelected()) {
            variedadeAnimais++;
            animaisMarcados += "Bovídeos / ";
        }
        if (jcbBoys.isSelected()) {
            variedadeAnimais++;
            animaisMarcados += "Bovinos / ";
        }
        if (jcbPoicos.isSelected()) {
            variedadeAnimais++;
            animaisMarcados += "Suínos / ";
        }
        if (jcbPeixis.isSelected()) {
            variedadeAnimais++;
            animaisMarcados += "Psídeos / ";
        }
        if (jcbPibis.isSelected()) {
            variedadeAnimais++;
            animaisMarcados += "Aves / ";
        }
        jLabel2.setText("Você tem o total de " + variedadeAnimais + " variedades de animais em sua propriedade:");
        jLabel3.setText("São elas: " + animaisMarcados);
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jcbBoysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBoysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBoysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JCheckBox jcbBoys;
    private javax.swing.JCheckBox jcbOveias;
    private javax.swing.JCheckBox jcbPeixis;
    private javax.swing.JCheckBox jcbPibis;
    private javax.swing.JCheckBox jcbPoicos;
    private javax.swing.JCheckBox jcbVacalos;
    // End of variables declaration//GEN-END:variables
}
